<html>
  <head>
    <title>si</title>
    <center><b><i><font face="Algerian">calculate the simple interest<br>
    <script language="JavaScript">
    var p,r,t,si;
    p=eval(prompt("enter principle amount:-"));
    r=eval(prompt("enter rate of interest:-"));
    t=eval(prompt("enter time:-"));
    si=(p*r*t)/100;
    document.write("the simple interest is :-"+si);
    </script>
    </head>
    </html>
